const HIDE_BLOCK_ANIMATION = 'hide 0.3s';
const SHOW_BLOCK_ANIMATION = 'show 0.3s';
const SHOW_WELCOME_ANIMATION = 'show 0.5s';
const SHOW_CARD_ANIMATION = 'showCard 0.5s';
const SHOW_MODAL_ANIMATION = 'showModal 0.3s';
const HIDE_MODAL_ANIMATION = 'hideModal 0.3s';
const HIDDEN_CLASS = 'hidden';

export {
  HIDE_BLOCK_ANIMATION,
  SHOW_BLOCK_ANIMATION,
  SHOW_WELCOME_ANIMATION,
  SHOW_CARD_ANIMATION,
  SHOW_MODAL_ANIMATION,
  HIDE_MODAL_ANIMATION,
  HIDDEN_CLASS,
};
